import { useState, useMemo, useRef } from "react";
import { BookOpen, ChevronDown, FileText, Lightbulb, Printer } from "lucide-react";
import ClassLevelSelector from "@/components/ClassLevelSelector";
import { topics } from "@/data/topics";
import { topicNotes } from "@/data/notes";
import { Button } from "@/components/ui/button";

const subjectLabels: Record<string, string> = {
  math: "Mathematics",
  physics: "Physics",
  chemistry: "Chemistry",
  biology: "Biology",
};

const subjectColors: Record<string, string> = {
  math: "bg-math",
  physics: "bg-physics",
  chemistry: "bg-chemistry",
  biology: "bg-biology",
};

const subjectBorders: Record<string, string> = {
  math: "border-l-math",
  physics: "border-l-physics",
  chemistry: "border-l-chemistry",
  biology: "border-l-biology",
};

const Notes = () => {
  const [selectedSubject, setSelectedSubject] = useState("math");
  const [selectedLevel, setSelectedLevel] = useState(1);
  const [expandedTopic, setExpandedTopic] = useState<string | null>(null);
  const printRef = useRef<HTMLDivElement>(null);

  const filteredTopics = useMemo(
    () => topics.filter((t) => t.subject === selectedSubject && t.level === selectedLevel),
    [selectedSubject, selectedLevel]
  );

  const handlePrint = () => {
    const printContent = filteredTopics.map((topic) => {
      const note = topicNotes.find((n) => n.topicId === topic.id);
      if (!note) return "";

      const formulas = topic.formulas?.length
        ? `<div style="margin:12px 0;"><strong>Key Formulas:</strong><br/>${topic.formulas.map(f => `<code style="background:#f0f0f0;padding:2px 8px;margin:2px 4px;border-radius:4px;font-family:monospace;">${f}</code>`).join(" ")}</div>`
        : "";

      const sections = note.sections.map(s =>
        `<div style="margin:8px 0;"><strong>${s.heading}</strong><p style="margin:4px 0;color:#333;">${s.content}</p></div>`
      ).join("");

      const examples = note.examples?.length
        ? `<div style="margin:12px 0;padding:12px;background:#f8f8f0;border-radius:8px;border:1px solid #e0e0d0;">
            <strong>Worked Examples</strong>
            ${note.examples.map(ex => `<div style="margin:8px 0;"><p><strong>Q:</strong> ${ex.problem}</p><p><strong>A:</strong> ${ex.solution}</p></div>`).join("")}
          </div>`
        : "";

      const keyPoints = `<div style="margin:12px 0;"><strong>Summary Points</strong><ul style="margin:4px 0;padding-left:20px;">${topic.keyPoints.map(p => `<li style="margin:2px 0;color:#333;">${p}</li>`).join("")}</ul></div>`;

      return `
        <div style="page-break-inside:avoid;margin:16px 0;padding:16px;border:1px solid #ddd;border-radius:8px;">
          <h2 style="margin:0 0 4px 0;color:#1a1a2e;">${topic.title}</h2>
          <p style="margin:0 0 8px 0;color:#666;font-size:14px;">${topic.description}</p>
          ${formulas}
          ${sections}
          ${examples}
          ${keyPoints}
        </div>
      `;
    }).join("");

    const printWindow = window.open("", "_blank");
    if (!printWindow) return;

    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
      <head>
        <title>${subjectLabels[selectedSubject]} S.${selectedLevel} - Study Notes | Sci-Sci-matic</title>
        <style>
          body { font-family: 'Segoe UI', system-ui, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px; color: #1a1a2e; }
          h1 { text-align: center; margin-bottom: 4px; }
          .subtitle { text-align: center; color: #666; margin-bottom: 24px; font-size: 14px; }
          code { font-size: 13px; }
          @media print {
            body { padding: 0; }
            div { page-break-inside: avoid; }
          }
        </style>
      </head>
      <body>
        <h1>📚 ${subjectLabels[selectedSubject]} — Senior ${selectedLevel}</h1>
        <p class="subtitle">Sci-Sci-matic Study Notes • Uganda Secondary Curriculum</p>
        ${printContent || "<p style='text-align:center;color:#999;'>No notes available for this selection yet.</p>"}
        <p style="text-align:center;color:#999;margin-top:32px;font-size:12px;">Generated by Sci-Sci-matic • sci-sci-matic.lovable.app</p>
      </body>
      </html>
    `);
    printWindow.document.close();
    printWindow.focus();
    setTimeout(() => printWindow.print(), 300);
  };

  return (
    <div className="mx-auto min-h-screen max-w-4xl px-4 py-8">
      <div className="mb-8 flex flex-wrap items-start justify-between gap-4">
        <div>
          <h1 className="mb-2 text-2xl font-bold text-foreground md:text-3xl">
            <FileText className="mr-2 inline h-7 w-7 text-primary" />
            Study Notes
          </h1>
          <p className="text-muted-foreground">Comprehensive notes following the Uganda secondary curriculum</p>
        </div>
        <Button onClick={handlePrint} variant="outline" className="gap-2">
          <Printer className="h-4 w-4" />
          Print / Save PDF
        </Button>
      </div>

      {/* Subject tabs */}
      <div className="mb-6 flex flex-wrap gap-2">
        {Object.entries(subjectLabels).map(([key, label]) => (
          <button
            key={key}
            onClick={() => { setSelectedSubject(key); setExpandedTopic(null); }}
            className={`rounded-lg px-4 py-2 text-sm font-semibold transition-all ${
              selectedSubject === key
                ? `${subjectColors[key]} text-primary-foreground shadow-md`
                : "bg-muted text-muted-foreground hover:bg-muted/80"
            }`}
          >
            {label}
          </button>
        ))}
      </div>

      {/* Class level */}
      <div className="mb-8">
        <p className="mb-2 text-sm font-medium text-muted-foreground">Class Level</p>
        <ClassLevelSelector selected={selectedLevel} onChange={(l) => { setSelectedLevel(l); setExpandedTopic(null); }} />
      </div>

      {/* Notes list */}
      <div className="space-y-4" ref={printRef}>
        {filteredTopics.length === 0 ? (
          <div className="rounded-xl border border-border bg-card p-8 text-center">
            <BookOpen className="mx-auto mb-3 h-10 w-10 text-muted-foreground/50" />
            <p className="text-muted-foreground">Notes coming soon for {subjectLabels[selectedSubject]} S.{selectedLevel}!</p>
          </div>
        ) : (
          filteredTopics.map((topic) => {
            const note = topicNotes.find((n) => n.topicId === topic.id);
            const isExpanded = expandedTopic === topic.id;

            return (
              <div
                key={topic.id}
                className={`overflow-hidden rounded-xl border border-border bg-card shadow-sm transition-shadow hover:shadow-md ${subjectBorders[selectedSubject]} border-l-4`}
              >
                <button
                  onClick={() => setExpandedTopic(isExpanded ? null : topic.id)}
                  className="flex w-full items-center justify-between p-5 text-left"
                >
                  <div className="flex-1">
                    <h3 className="text-lg font-semibold text-foreground">{topic.title}</h3>
                    <p className="mt-1 text-sm text-muted-foreground">{topic.description}</p>
                    {note && (
                      <span className="mt-2 inline-flex items-center gap-1 text-xs font-medium text-primary">
                        <FileText className="h-3 w-3" />
                        {note.sections.length} sections
                        {note.examples && ` · ${note.examples.length} worked example${note.examples.length > 1 ? "s" : ""}`}
                      </span>
                    )}
                  </div>
                  <ChevronDown className={`ml-4 h-5 w-5 shrink-0 text-muted-foreground transition-transform ${isExpanded ? "rotate-180" : ""}`} />
                </button>

                {isExpanded && note && (
                  <div className="border-t border-border bg-muted/20 px-5 py-6 space-y-6">
                    {/* Key Formulas */}
                    {topic.formulas && topic.formulas.length > 0 && (
                      <div>
                        <h4 className="mb-2 text-sm font-semibold text-primary flex items-center gap-1">
                          <span className="inline-block h-1.5 w-1.5 rounded-full bg-primary" />
                          Key Formulas
                        </h4>
                        <div className="flex flex-wrap gap-2">
                          {topic.formulas.map((f, i) => (
                            <code key={i} className="rounded-md bg-primary/10 px-3 py-1.5 text-sm font-mono font-semibold text-primary">
                              {f}
                            </code>
                          ))}
                        </div>
                      </div>
                    )}

                    {/* Note Sections */}
                    {note.sections.map((section, i) => (
                      <div key={i}>
                        <h4 className="mb-1.5 text-sm font-bold text-foreground">{section.heading}</h4>
                        <p className="text-sm leading-relaxed text-muted-foreground">{section.content}</p>
                      </div>
                    ))}

                    {/* Worked Examples */}
                    {note.examples && note.examples.length > 0 && (
                      <div className="rounded-lg border border-secondary/30 bg-secondary/5 p-4">
                        <h4 className="mb-3 flex items-center gap-2 text-sm font-bold text-secondary">
                          <Lightbulb className="h-4 w-4" />
                          Worked Examples
                        </h4>
                        <div className="space-y-3">
                          {note.examples.map((ex, i) => (
                            <div key={i} className="text-sm">
                              <p className="font-medium text-foreground">Q: {ex.problem}</p>
                              <p className="mt-1 text-muted-foreground"><span className="font-semibold text-primary">A:</span> {ex.solution}</p>
                            </div>
                          ))}
                        </div>
                      </div>
                    )}

                    {/* Key Points */}
                    <div>
                      <h4 className="mb-2 text-sm font-bold text-foreground">Summary Points</h4>
                      <ul className="grid gap-1.5 sm:grid-cols-2">
                        {topic.keyPoints.map((point, i) => (
                          <li key={i} className="flex items-start gap-2 text-sm text-muted-foreground">
                            <span className="mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full bg-secondary" />
                            {point}
                          </li>
                        ))}
                      </ul>
                    </div>
                  </div>
                )}

                {isExpanded && !note && (
                  <div className="border-t border-border bg-muted/20 px-5 py-6 text-center">
                    <p className="text-sm text-muted-foreground">Detailed notes coming soon for this topic.</p>
                  </div>
                )}
              </div>
            );
          })
        )}
      </div>
    </div>
  );
};

export default Notes;
